version: '3.6'

services:
  elk:
    image: sebp/elk
    ports:
      - "9200:9200" # Elasticsearch
      - "5044:5044" # Logstash
      - "5601:5601" # Kibana
    volumes:
      - ./elasticsearch/elk-data:/var/lib/elasticsearch
      - ./logstash/conf.d:/etc/logstash/conf.d
      - ./logs:/var/log/elk-source
